### ISSUE TITLE
Test the REST API -- Connection Refused Issue

### ISSUE THREAD

**Issue by jnevin** [tleyden/open-ocr#26]
Everything good in install up to point of "Test the REST API" -- where I get a "connection refused"

For the curl command, I am substituting my local IP address (at this time, 10.58.105.52) for the example's IP, so:
`curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://10.58.105.52:$HTTP_PORT/ocr`

I get a:
`Failed to connect to 10.58.105.52 port 8080: Connection refused`

Any clues?

**Comment by lostpupil** [comment]
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://0.0.0.0:8080/ocr
curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused

I am following instruction here, and got this error when testing locally.
And there is the 44th line mapping there

I am using osx boot2docker

**Comment by tleyden** [comment]
I haven't tried on boot2docker, but 0.0.0.0 looks like an invalid address  (or is that from boot2docker documentation?)

What about 127.0.0.1:8080?

**Comment by lostpupil** [comment]
@tleyden not work either. I am a little bit confused here.

**Comment by wedkarz** [comment]
I have similiar problem. I've checked 127.0.0.1:9292 and localhost:9292.
I have created instances using docker-machine on osx. 
Here is **docker ps** result:

```
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
7086f4b1f569        tleyden5iwx/open-ocr                "/opt/open-ocr/open-o"   34 minutes ago      Up 28 minutes       0.0.0.0:9292->9292/tcp   dockercompose_openocr_1
073e0fb08b65        tleyden5iwx/open-ocr-preprocessor   "/opt/open-ocr/open-o"   34 minutes ago      Up 28 minutes                                dockercompose_strokewidthtransform_1
614d0df1ff2b        tleyden5iwx/open-ocr                "/opt/open-ocr/open-o"   34 minutes ago      Up 28 minutes                                dockercompose_openocrworker_1
b6accfeba49b        tutum/rabbitmq                      "/run.sh"                34 minutes ago      Up 28 minutes       5672/tcp, 15672/tcp      dockercompose_rabbitmq_1

```

**docker top** on first container:
```
PID                 USER                COMMAND
4422                root                {open-ocr-httpd} /bin/sh /opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292
4533                root                open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292
4972                root                bash

```

**Comment by nicktackes** [comment]
Hello (and thanks for providing this project),

I'm adding to this issue because I also get to the testing of the curl request on local.
docker machine env ....
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/nicktackes/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

documentation indicates 
HTTP_POST is the port number inside the .yml file inside the docker-compose directory presuming it should be the same 9292.
...
    ports:
      - "9292:9292"

running the curl
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://192.168.99.100:9292/ocr

curl: (7) Failed to connect to 192.168.99.100 port 9292: Connection refused

any advice is appreciated.

**Comment by tleyden** [comment]
@nicktackes can you open a new ticket for this?  I think at the very least the docs should be improved.
