### ISSUE TITLE
Unable to perform OCR decode.  Error: Get http://bit.ly/ocrimage: dial tcp: lookup bit.ly: no such host

### ISSUE THREAD

**Issue by bx5974** [tleyden/open-ocr#29]
root@admaticvel:/home/admatic# docker run -d -p 5672:5672 -p 15672:15672 -e RABBITMQ_PASS=mypass tutum/rabbitmq

root@admaticvel:/home/admatic# docker run -d -p 8080:8080 tleyden5iwx/open-ocr open-ocr-httpd -amqp_uri "amqp://admin:mypass@172.16.0.2/" -http_port 8080

root@admaticvel:/home/admatic# docker  run -d tleyden5iwx/open-ocr open-ocr-worker -amqp_uri "amqp://admin:mypass@172.16.0.2/"

root@admaticvel:/home/admatic# curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://172.16.0.2:8080/ocr

Unable to perform OCR decode.  Error: Get http://bit.ly/ocrimage: dial tcp: lookup bit.ly: no such host

But, i can do a wget of the same URL ( == means Internet connection is working)

**Comment by tleyden** [comment]
That sounds like some sort of strange dns issue.

Try uploading your own test image to your own website (or a github gist or something).  

Are you on vagrant?

Also, try running "docker logs --follow <container id>" on both the worker and httpd processes.

Closing this, because I think its a network setup issue and not an openocr bug.  But feel free to comment on the ticket.
