### ISSUE TITLE
OCR precision vs Image accuracy - Tuning

### ISSUE THREAD

**Issue by gnovelli** [tleyden/open-ocr#30]
As stated on the comments of the related docker repository page (https://registry.hub.docker.com/u/tleyden5iwx/open-ocr/):

I see that ocr precision increases with image size without changing the original image accuracy. 

Is it possible to tune ocr precision through any rest parameter?

Tested on a short italian text captured through different screenshots of the same web page.

I have just checked the REST API documentation but I haven't seen such a thing. 

Regards, Giovanni

**Comment by tleyden** [comment]
Since openocr just wraps Tesseract, this feature would need to be exposed in Tesseract first.  Can you ask on https://groups.google.com/forum/#!forum/tesseract-ocr and re-open this ticket if there is way to do the tuning you need?

I'm closing the ticket, but I will re-open if there is an action item.  Feel free to continue the discussion on this ticket.

**Comment by gnovelli** [comment]
Ok, thanks for the feedback. Firstly I check on forums. I see that parameterization should be needed for more reasons than the above. For example normally, having an image, we need to keep page format too and extract not only text, to use such a service in a production environment. Regards, Giovanni
