### ISSUE TITLE
Unable to perform OCR decode.  Error: dial tcp

### ISSUE THREAD

**Issue by 1905** [tleyden/open-ocr#42]
After install host is saying
**OpenOCR is running!**

But POST request is failing
`Unable to perform OCR decode.  Error: dial tcp <hostip>:5672: no route to host`

my system:
Ubuntu 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker:
Docker version 1.7.1, build 786b29d

**Comment by arinbec** [comment]
Same error here too. I think the problem is with Docker not configured correctly with dns. It has something to do with dnsmasq and dns set to 127.0.0.1 in resolv.conf file. Tried many options but could not fix it. Ideally it should not require any changes as it breaks the portability advantage  of Docker.

**Comment by tleyden** [comment]
@1905 how are you installing it?  launch.sh or docker compose?  Also, vagrant or GCE or AWS ..?

**Comment by harryprince** [comment]
I have the same problem, and I run it on my Mac with Beta Native Docker.

**Comment by tleyden** [comment]
@harryprince or @1905 -- are you using docker compose?  How are you launching?

**Comment by harperjuanl** [comment]
Changing the image url is working for me:  
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://tleyden-misc.s3.amazonaws.com/blog_images/ocr_test.png","engine":"tesseract"}' http://xxxx/ocr

**Comment by tleyden** [comment]
@harperjuanl Oops, I must've changed the permissions on that image.  I will fix the example, thanks!
