### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by MichaelF25** [tleyden/open-ocr#87]
Hi,

are there any plans to add `application/pdf` as supported `Content-type` within the `multipart/related` request?
Maybe it's enough to add ghostscript to the tesseract docker image (if it's not already present) and adjust the `Content-type` check in the http handler.

**Comment by tleyden** [comment]
No plans but it sounds like a useful feature 

Does ghostscript just render pdf -> image?

**Comment by MichaelF25** [comment]
To be honest, I am not sure. I've just evaluated tesseract via command line for my use case (OCR for my PDFs) and it worked out of the box if ghostscript was also installed on the system. This leads me to my initial assumption above.

**Comment by Afterburned6387** [comment]
I'll second this as a feature request. Ghostscript compiles pdf -> postscript, but there are lots of tools that can convert the .ps file to .png, .tiff, etc. 

Honestly, if you're using PDF's, chances are the PDF is just a wrapper for .TIFF images that can be directly extracted without any resampling/processing.  Python's PyPDF2 package can retrieve these:

https://stackoverflow.com/questions/2693820/extract-images-from-pdf-without-resampling-in-python

Unfortunately, Go is complete greek to me, so I don't know how to do something similar in Go. Alternatively, are there any plans or ideas on how to integrate python preprocessor modules? This seems like a good candidate. I could (and already am) taking PDFs of government documents, stripping out tiffs in my applications. OCR is just the one missing step (and why I landed here).

**Comment by Afterburned6387** [comment]
Update: Much faster image extraction can be done with poppler using the pdfimages command. And Tesseract doesn't complain about the output.

**Comment by sferoze** [comment]
@Afterburned6387 

I would like to also pass PDF document links to openOCR. Like so: 

`curl -X POST -H "Content-Type: application/json" -d '{"pdf_url":"http://bit.ly/ocrpdf","engine":"tesseract"}' http://IP_ADDRESS_OF_DOCKER_HOST:HTTP_PORT/ocr`

Just instead of `img_url` in the body it is `pdf_url`

Anyone have a rough outline of how I would implement this addition?

**Comment by tleyden** [comment]
@sferoze the current infrastructure in place for this is to create a [preprocessor like the Stroke Width Transform](https://github.com/tleyden/open-ocr/wiki/Stroke-Width-Transform) and add it to the pipeline.  This would require some coding.

**Comment by TukaramKanade** [comment]
Hi All,
Any update on the PDF support, is it included ? If yes , could you please provide the details on it.

**Comment by tleyden** [comment]
@TukaramKanade not that I'm aware of

**Comment by xf0e** [comment]
Since tesseract 4 has no support for reading pdf files, and we need to handle them i managed to create a new preprocessor convert-pdf for this purpose.

https://github.com/xf0e/open-ocr/blob/master/convert-pdf.go

It will convert an incoming PDF file with ImageMagick an pass it to tesseract_engine.

I hope it helps.

**Comment by xf0e** [comment]
@tleyden Done! https://github.com/tleyden/open-ocr/pull/108
